// apps/web/src/hooks/useVisitorState.ts
'use client';

import { useState, useEffect, useCallback } from 'react';
import { PortfolioAddress } from '@/lib/supabase/types';

/**
 * Visitor portfolio data stored in localStorage
 */
interface VisitorPortfolio {
  addresses: Array<{
    address: string;
    label: string;
    chainId: string;
    addedAt: string;
  }>;
  lastViewed: string;
}

const VISITOR_STORAGE_KEY = 'shieldnest_visitor_portfolio';

/**
 * Hook to manage visitor state in localStorage
 * Tracks addresses and shows upgrade prompts
 */
export function useVisitorState() {
  const [portfolio, setPortfolio] = useState<VisitorPortfolio>({
    addresses: [],
    lastViewed: new Date().toISOString(),
  });
  const [hasBeenNudged, setHasBeenNudged] = useState(false);

  // Load visitor data from localStorage
  useEffect(() => {
    if (typeof window === 'undefined') return;

    try {
      const stored = localStorage.getItem(VISITOR_STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        setPortfolio(parsed);
      }
    } catch (error) {
      console.error('Failed to load visitor state:', error);
    }

    // Check if user has been nudged before
    const nudged = localStorage.getItem('shieldnest_nudged');
    setHasBeenNudged(!!nudged);
  }, []);

  // Save portfolio to localStorage
  const savePortfolio = useCallback((newPortfolio: VisitorPortfolio) => {
    if (typeof window === 'undefined') return;

    try {
      localStorage.setItem(VISITOR_STORAGE_KEY, JSON.stringify(newPortfolio));
      setPortfolio(newPortfolio);
    } catch (error) {
      console.error('Failed to save visitor state:', error);
    }
  }, []);

  // Add address to visitor portfolio
  const addAddress = useCallback((address: string, label: string, chainId: string) => {
    const newPortfolio: VisitorPortfolio = {
      addresses: [
        ...portfolio.addresses.filter(a => a.address !== address),
        {
          address,
          label: label || `Address ${portfolio.addresses.length + 1}`,
          chainId,
          addedAt: new Date().toISOString(),
        },
      ],
      lastViewed: new Date().toISOString(),
    };
    
    savePortfolio(newPortfolio);
  }, [portfolio, savePortfolio]);

  // Remove address from visitor portfolio
  const removeAddress = useCallback((address: string) => {
    const newPortfolio: VisitorPortfolio = {
      ...portfolio,
      addresses: portfolio.addresses.filter(a => a.address !== address),
      lastViewed: new Date().toISOString(),
    };
    
    savePortfolio(newPortfolio);
  }, [portfolio, savePortfolio]);

  // Clear all visitor data
  const clearVisitorData = useCallback(() => {
    if (typeof window === 'undefined') return;

    try {
      localStorage.removeItem(VISITOR_STORAGE_KEY);
      localStorage.removeItem('shieldnest_nudged');
      setPortfolio({ addresses: [], lastViewed: new Date().toISOString() });
      setHasBeenNudged(false);
    } catch (error) {
      console.error('Failed to clear visitor state:', error);
    }
  }, []);

  // Mark as nudged to prevent future nudges
  const markAsNudged = useCallback(() => {
    if (typeof window === 'undefined') return;

    try {
      localStorage.setItem('shieldnest_nudged', 'true');
      setHasBeenNudged(true);
    } catch (error) {
      console.error('Failed to mark as nudged:', error);
    }
  }, []);

  // Check if user should be shown upgrade prompt
  const shouldShowUpgradePrompt = useCallback(() => {
    if (hasBeenNudged) return false;
    if (portfolio.addresses.length === 0) return false;
    
    // Show prompt if user has added addresses but not signed up
    return portfolio.addresses.length >= 1;
  }, [hasBeenNudged, portfolio.addresses.length]);

  // Get visitor session age
  const getSessionAge = useCallback(() => {
    if (portfolio.addresses.length === 0) return 0;
    
    const oldestAddress = portfolio.addresses.reduce((oldest, current) => {
      return new Date(current.addedAt) < new Date(oldest.addedAt) ? current : oldest;
    });
    
    return Date.now() - new Date(oldestAddress.addedAt).getTime();
  }, [portfolio.addresses]);

  // Migrate visitor data to user account
  const migrateToUserAccount = useCallback(async (userId: string): Promise<PortfolioAddress[]> => {
    const addresses: PortfolioAddress[] = portfolio.addresses.map(addr => ({
      id: '', // Will be generated by DB
      user_id: userId,
      chain_id: addr.chainId,
      address: addr.address,
      label: addr.label,
      created_at: addr.addedAt,
    }));

    // Clear visitor data after successful migration
    clearVisitorData();
    
    return addresses;
  }, [portfolio.addresses, clearVisitorData]);

  return {
    portfolio,
    addAddress,
    removeAddress,
    clearVisitorData,
    markAsNudged,
    shouldShowUpgradePrompt,
    getSessionAge,
    migrateToUserAccount,
    hasAddresses: portfolio.addresses.length > 0,
  };
}
